name: unit-test

on:
  pull_request:
    branches: [master]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Front-end build
        run: |
          npm install
          npm run test
          npm run codecov

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions/setup-go@v1
        with:
          go-version: '^1.15.5'
      - name: Back-end build
        run: |
          go version
          npm install
          npm run test-backend
